// Re-shapes the backlog after the decision "MQ is a Quarkus-native product, free of R2 and Mason": configuration, security, CORS, metrics,
// OpenAPI and more come from Quarkus; the XML is redesigned. See docs/spec/project-spec.md (draft 2) and docs/reports/quarkus-leverage.md.
// Run once.
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const gh = (...a) => execFileSync('gh', a, { maxBuffer: 64 * 1024 * 1024 }).toString().trim();
const list = JSON.parse(gh('issue', 'list', '--state', 'all', '--limit', '200', '--json', 'number,title,state'));
const find = (frag) => {
  const hits = list.filter((i) => i.title.includes(frag));
  if (hits.length !== 1) { console.log(`!! ${hits.length} matches for "${frag}"`); return null; }
  return hits[0].number;
};
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'issues3-'));
let n = 0;
const file = (text) => { const f = path.join(tmp, `${++n}.md`); fs.writeFileSync(f, text + '\n'); return f; };
const run = (...a) => { try { console.log(gh(...a)); } catch (e) { console.log('FAILED ' + a.slice(0, 3).join(' ') + ': ' + e.message.split('\n')[0]); } };
const D = 'Decision: MQ is a Quarkus-native product, free of R2 and Mason; Quarkus features are used as they are where they exist (docs/spec/project-spec.md draft 2, docs/reports/quarkus-leverage.md).';

const edit = (frag, title, body, add, remove) => {
  const num = find(frag); if (!num) return;
  const a = ['issue', 'edit', String(num), '--title', title, '--body-file', file(D + '\n\n' + body)];
  if (add) a.push('--add-label', add);
  if (remove) a.push('--remove-label', remove);
  run(...a);
};
const close = (frag, comment) => { const num = find(frag); if (num) run('issue', 'close', String(num), '--reason', 'not planned', '--comment', comment); };
const create = (title, labels, body) => run('issue', 'create', '--title', title, '--body-file', file(D + '\n\n' + body), '--label', labels);

// ---------------------------------------------------------------- existing issues
edit('Read mq.yaml', 'Configuration: an mq: section in application.yaml as a typed ConfigMapping, unknown keys are errors',
  'The custom `mq.yaml` reader is dropped. Quarkus reads `application.yaml` (verified in native), which already gives profiles (`%dev`, `%prod`), environment variables, secrets and ConfigMaps. MQ settings live under `mq:` as a `@ConfigMapping`; an unknown key under `mq:` fails the start naming the key (Quarkus only warns for unknown keys elsewhere: `quarkus.http.cors` was silently ignored in the spike).\n\nSections: `api`, `scripts`, `lib`, `libs`, `properties`, `datasources`, `migrations`, `auth`, `strictParams`, `xrequest`. The CLI reads the same file at build time to choose drivers and libraries.\n\nAcceptance: the shop and bookstore samples run from `application.yaml` alone; bad keys and missing `${ENV}` values fail with a clear message.', 'v1', null);
edit('Datasources from mq.yaml', 'Datasources from mq.datasources (programmatic Agroal), named per step, with pool metrics and health',
  'Spike 3: Agroal pools created at boot from configuration work on the JVM and in native, a failing datasource does not stop the process. Create them from `mq.datasources` so one Dev runtime can host any project; honour `datasource="name"` on `Sql`, `Transaction` and script `db`; register pool metrics and a health check for them (Quarkus-managed datasources would give both but fix the database kind at build time).\n\nOpen decision: dynamic datasources (this) versus Quarkus-managed named datasources generated by the CLI for production. Record the outcome in docs/decisions.md.\n\nAcceptance: PostgreSQL and HSQLDB in one project, JVM and native, `/q/health` and metrics show both pools.', 'v1', null);
edit('Response shaping', 'Respond element: state the response and compose nested JSON from steps',
  'Replaces "every output step becomes a key". `<Respond status body="$[books]"/>` or a template `{ "book": $[book][0], "reviews": $[reviews] }`; without it the last step is the response; scripts do the rest. Found by the bookstore exercise (docs/reports/bookstore-exercise.md, items 1 and 2). Part of the XML redesign issue.', 'v1', null);
edit('Authentication and authorization', 'Authentication: Quarkus JWT and OIDC, and script providers, behind the auth attribute',
  'Verified in native: JWT verification with a static key protects routes added by code through `quarkus.http.auth.permission.*`; wrong issuer and expired tokens give 401; the principal comes from `QuarkusHttpUser.getSecurityIdentity(rc, null)` (a `Uni`, await it in a blocking handler). Still to verify: OIDC against a real provider (use Dev Services Keycloak).\n\nMQ part: an `auth="name"` attribute on `Resource` and `Request` choosing a provider from `mq.auth.providers` (`jwt`, `oidc`, `script`), roles from claims, the principal for scripts as `request.uid`/`request.roles`. Script providers are covered by the script-backed extension points issue.', 'v1', null);
edit('Database migrations and seed', 'Migrations: a per-datasource Flyway runner (the Quarkus extension misapplies named locations)',
  'Finding (docs/reports/quarkus-leverage.md): with the Quarkus Flyway extension, the `filesystem:` location configured for the named datasource `reports` was also applied to the default datasource (version 101 from the reports folder appeared in `main`), in YAML and properties syntax, on the JVM and in native. A migration on the wrong database is dangerous.\n\nMQ runs the Flyway library itself, once per datasource, with `db/migrations/<datasource>/V<n>__<name>.sql`, refuses to serve when one fails, and `db/seed` only in the dev profile. The Dev server migrates at start, the CLI bundles the files, the binary applies them at start or `mq migrate`.\n\nAcceptance: two datasources with different migration folders never see each other\'s files; works against an empty database on PostgreSQL and HSQLDB, JVM and native.', 'v1', null);
close('HTTP settings in mq.yaml', 'Provided by Quarkus configuration, no MQ work: CORS and body limits are verified in native (docs/reports/quarkus-leverage.md); profiles are Quarkus profiles; the XRequest timeout is `mq.xrequest.timeoutSeconds`.');
edit('mq docs: OpenAPI 3', 'mq docs: build the OpenAPI document from the XML with SmallRye\'s model reader',
  'Verified in native: an `OASModelReader` builds the OpenAPI model in code and `/openapi` serves it (docs/reports/quarkus-leverage.md). Build the model from the MQ model: paths from `Resource`/`Request` `path`, `Param in=` and types and limits, statuses, `Desc`. Swagger UI in dev. `mq docs` writes the file.', 'v1', null);
edit('Strict parameters', 'Strict parameters: reject any query, body or header value a request does not declare',
  'With `Param in=` (XML redesign) every accepted value is declared, so a misspelled parameter can be refused with a 400 naming it. `mq.strictParams: true` turns it on; default on in production.', null, null);
edit('Observability: metrics', 'Metrics, health and tracing: Micrometer, health checks and OpenTelemetry wired to requests and steps',
  'Metrics (Micrometer + Prometheus) and health are verified in native. MQ part: a timer and counter per request and per step (labelled by resource, request, step id and outcome), the datasource pools as health and metrics, an `errorId` in log lines. OpenTelemetry: one span per request and step; needs its own native check.', 'v1', 'future');
edit('Run what is validated but ignored', 'Re-decide onblank, ref (SQL catalog) and Param exists in the new XML',
  'These are R2 features. With a clean sheet, decide for each: keep with a precise meaning, replace (`<Error when=...>` covers onblank), or drop. Do not implement the R2 behaviour just because it existed.', null, null);
close('item attribute: any value', 'Obsolete: the redesign replaces `item` and `parent` with explicit `path` attributes on `Resource` and `Request` (XML redesign issue).');
edit('mpath row index base', 'mpath row index base: write it into the spec and warn on likely 1-based use',
  'The index is 0-based (decided). With the XML redesign, document it where `$[step][0]` is introduced and add a validator warning when a `[n]` on a query result looks 1-based.', null, null);

// ---------------------------------------------------------------- new issues
create('Redesign the XML (v2): explicit routes, Param in=, Respond, Error, generated keys', 'enhancement,v1,spec,validator,engine',
  'Draft in docs/spec/project-spec.md section 4. Explicit `path` on `Resource` and `Request` (no `item`, `parent`, version attribute); `Param in="query|path|body|header"`; `<Respond>`; `<Error when status message/>`; update steps expose `$[ins].id`; more `Param` types (`integer`, `decimal`, `boolean`, `uuid`). Keep `$param`, `$[step].path`, `when`, `Sql`, `Transaction`, `XRequest`, `Script`, `Text`.\n\nOwner decisions needed on the proposal details (namespace `urn:mq:api:1`, element names, how templates in `Respond` are written). Then: new model, validator, executors, golden suite, bookstore and shop samples ported.\n\nAcceptance: the bookstore and shop run on the new syntax, JVM and native, with the old tests ported.');
create('Publish an XSD for the new syntax and rewrite the golden suite against it', 'enhancement,v1,validator',
  'R2\'s `resource.xsd` and the oracle (`tools/xsd-oracle`) go away. Author `mq-api-1.xsd` for `urn:mq:api:1` (editor completion, validation in IDEs), keep the MQ rules the schema cannot express (mpath references, ids, `when` syntax, script names), regenerate `golden/` from the new vocabulary and keep the real-resource corpus as migrated files.');
create('Migration tool: R2 resource XML to the new syntax', 'enhancement,future,cli',
  '`mq migrate-xml old.xml` rewrites R2 files (`item`, `parent`, `v`, flat outputs) into the new syntax and lists what needs a human decision. The 35 real R2 resources are the test corpus. Only if someone has R2 files worth keeping.');
create('Decide: MQ-created datasources or Quarkus-managed named datasources', 'question,v1,spec,dev-server,cli',
  'Programmatic Agroal (Spike 3) suits one Dev runtime hosting any project but needs MQ to add pool metrics and health. Quarkus-managed named datasources give both and Dev Services but fix the database kind at build time, which suits the CLI\'s per-project native build. Candidate answer: programmatic in the Dev runtime, generated `quarkus.datasource.*` in the CLI build, one `mq.datasources` section as the source. Measure the cost of the two paths and decide.');
create('Native checks still missing for Quarkus features MQ wants', 'enhancement,v1,native',
  'Not yet verified in native (docs/reports/quarkus-leverage.md section 5): OIDC against Keycloak, OpenTelemetry export, Dev Services (JVM), SmallRye Fault Tolerance annotations, virtual threads, the container-image and Kubernetes extensions, and the Quarkus CLI codestart. One small spike each, same format as the leverage spike, before MQ depends on them.');
create('Resilience for XRequest: retry, timeout and circuit breaker attributes', 'enhancement,future,engine',
  'SmallRye Fault Tolerance offers retry, timeout, bulkhead and circuit breaker. Expose them as attributes on `XRequest` (`retry="3"`, `breaker="5/30s"`), implemented with the Quarkus API; needs a native check.');
create('Dev Services: databases started automatically in the Dev server', 'enhancement,v1,dev-server',
  'In dev mode Quarkus starts PostgreSQL and other containers by itself. Use it so a new project runs without a database set up by hand, with the migrations applied; fall back to HSQLDB in memory when no container runtime is present.');
create('Dev UI page for MQ: resources, steps, errors, reload state', 'enhancement,future,dev-server',
  'A Quarkus Dev UI page listing the loaded resources and routes, the last errors with their `errorId`, the reload history, script compile status and the shared scripting host.');
create('mq init as a Quarkus codestart and the CLI as a thin driver of the Quarkus build', 'enhancement,v1,cli',
  '`mq init` (and `quarkus create`) generate a project: `application.yaml`, `api/`, `scripts/`, `lib/`, `db/migrations/`, IDE setup. `mq build` drives the Quarkus native build in a Mandrel container (`quarkus.native.container-build`) instead of our own container script, adds the container image and Kubernetes extensions on request (ConfigMap for the XML folder, update and restart the pod).');
create('Virtual threads for blocking steps', 'enhancement,future,engine',
  'Run request handling on virtual threads (JDK 21 and later) so blocking JDBC and XRequest calls do not use up worker threads under load. Measure against the current worker pool, on the JVM and in native.');
create('Reproduce and report upstream: Flyway named datasource locations applied to the default datasource', 'bug,v1,security',
  'Minimal reproduction is `spikes/quarkus-leverage` (default on `classpath:db/migration`, named `reports` on `filesystem:`). Reduce it to a standalone project, test on the latest Quarkus 3.x, and report it to the Quarkus project with the reproduction (the report is public: review it first). MQ works around it with its own Flyway runner.');
