// THROWAWAY spike: writes ScriptRegistry.java, one entry per script, calling the compiled script class directly (no reflection).
// Java, because Kotlin does not let ordinary sources refer to the classes compiled from scripts.
import fs from 'node:fs';
import path from 'node:path';
const dir = process.argv[2] || 'scripts';
const out = process.argv[3] || 'build/gen/ScriptRegistry.java';
const names = fs.readdirSync(dir).filter((f) => f.endsWith('.kts')).map((f) => f.slice(0, -4)).sort();
const cls = (n) => n[0].toUpperCase() + n.slice(1);
const lines = names.map((n) => `        m.put("${n}", (p, s, r, q) -> new ${cls(n)}(p, s, r, q));`);
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, `import io.mq.script.Params;
import io.mq.script.RequestInfo;
import io.mq.script.Response;
import io.mq.script.Steps;
import java.util.LinkedHashMap;
import java.util.Map;

/** generated by gen.mjs: one factory per compiled script; calling the constructor runs the script body */
public final class ScriptRegistry {
    public interface Factory {
        Object create(Params p, Steps s, Response r, RequestInfo q);
    }

    public static final Map<String, Factory> scripts = new LinkedHashMap<>();

    static {
        Map<String, Factory> m = scripts;
${lines.join('\n')}
    }

    private ScriptRegistry() {
    }
}
`);
console.log('registry:', names.join(', '));
