CREATE TABLE IF NOT EXISTS movie (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, rating DECIMAL(3,1));
INSERT INTO movie (name, rating) SELECT 'Madagascar', 4.5 WHERE NOT EXISTS (SELECT 1 FROM movie);
